name: willfolio
description: Willard Shikami's Portfolio.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0+1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  progressive_image: ^2.0.0
  responsive_builder: ^0.4.1
  universal_html: ^2.0.8
  url_strategy: ^0.2.0
  platform: ^3.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/fonts/
  
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura_light_bt.ttf
          weight: 200
        - asset: assets/fonts/futura_medium_bt.ttf
          weight: 400
        - asset: assets/fonts/futura_book.ttf
          weight: 600
        - asset: assets/fonts/futura_extra_black.ttf
          weight: 600
        - asset: assets/fonts/futura_heavy.ttf
          weight: 900

    - family: Borgat
      fonts:
        - asset: assets/fonts/bogart/bogart_semibold.otf
          weight: 600

    - family: Rampant One
      fonts:
        - asset: assets/fonts/rampant/rampant_one.ttf
          weight: 400
