name: willfolio
description: Willard Shikami's Portfolio.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  platform: ^3.1.0
  progressive_image: ^2.0.0
  responsive_builder: ^0.4.1
  universal_html: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600

    - family: Bogart
      fonts:
        - asset: assets/fonts/bogart/bogart_semibold.otf
          weight: 600

    - family: Rampant One
      fonts:
        - asset: assets/fonts/rampant/rampant_one.ttf
          weight: 400
