name: willfolio
description: Willard Shikami's Portfolio.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura_light_bt.ttf
          weight: 200
        - asset: assets/fonts/futura_medium_bt.ttf
          weight: 400
        - asset: assets/fonts/futura_book.ttf
          weight: 600
        - asset: assets/fonts/futura_extra_black.ttf
          weight: 600
        - asset: assets/fonts/futura_heavy.ttf
          weight: 900

    - family: Orchide Regular
      fonts:
        - asset: assets/fonts/orchide.otf
          weight: 400
