name: willfolio
description: Willard Shikami's Portfolio.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  firebase_analytics: ^8.3.0
  progressive_image: ^1.0.1
  responsive_builder: ^0.4.1
  universal_html: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura_light_bt.ttf
          weight: 200
        - asset: assets/fonts/futura_medium_bt.ttf
          weight: 400
        - asset: assets/fonts/futura_book.ttf
          weight: 600
        - asset: assets/fonts/futura_extra_black.ttf
          weight: 600
        - asset: assets/fonts/futura_heavy.ttf
          weight: 900

    - family: Borgat
      fonts:
        - asset: assets/fonts/bogart/bogart_semibold.otf
          weight: 600

    - family: Rampant One
      fonts:
        - asset: assets/fonts/rampant/rampant_one.ttf
          weight: 400
